export const LOAD_CATEGORY = "LOAD_CATEGORY";
export const LOAD_SEARCHBOX_VALUE = "LOAD_SEARCHBOX_VALUE";
export const CHECKBOX_VALUE_CHANGE = "CHECKBOX_VALUE_CHANGE";
export const LOAD_SEARCHED_CATEGORY = "LOAD_SEARCHED_CATEGORY";