export const LOAD_ATTRIBUTES = "LOAD_ATTRIBUTES";
export const LOAD_SEARCHBOX_VALUE_ATTRIBUTES = "LOAD_SEARCHBOX_VALUE_ATTRIBUTES";
export const CHECKBOX_VALUE_CHANGE = "CHECKBOX_VALUE_CHANGE";
export const LOAD_ATTRIBUTES_SEARCHED = "LOAD_ATTRIBUTES_SEARCHED";