export const LOAD_CATEGORY_OF_CATEGORIES = "LOAD_CATEGORY_OF_CATEGORIES";
export const UPDATE_CATEGORY_CHNAGES = "UPDATE_CATEGORY_CHNAGES";
export const LOAD_CATEGORY_SUGGESTIONS = "LOAD_CATEGORY_SUGGESTIONS";